global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'payment-api'
    static_configs:
      - targets: ['APPLICATION_VM_IP:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s
